# -*- coding: utf-8 -*-
"""dio_santander_dev_week_2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N0Ganxy8H5Dl1QTdK84Up0s8vxJj2-WO

Introdução: Para o desafio foi solicitado o desenvolvimento da IA generativa em um diferente contexto. Para isso, utilizei diferentes recursos como a inteligência artificial Bing para a criação do contexto, o Mysql para o desenvolvimento do banco de dados, Colahb para o desenvolvimento em python além do Google Docs para armazenamento do banco em CSV. O desenvolvimento ocorreu comforme descrito abaixo.

Contexto:
Criação da empresa
(Utilizando o BING)

Empresa fictícia chamada Flora é uma floricultura online que entrega flores frescas e arranjos personalizados para os clientes. Aqui estão algumas informações sobre a empresa:
A missão da Flora é oferecer uma experiência única e encantadora para os amantes de flores, com produtos de alta qualidade, atendimento personalizado e entrega rápida.
A visão da Flora é se tornar a maior e mais confiável floricultura online do Brasil, expandindo sua presença para outras regiões e países.
Os valores da Flora são: paixão pelas flores, respeito pelos clientes, compromisso com a excelência, inovação e sustentabilidade.

A Flora foi fundada em 2020 por Ana e Bruno, dois amigos que compartilham o amor pelas flores e o sonho de empreender. Eles começaram a vender flores pela internet com um investimento inicial de R$ 10.000,00 e uma equipe de quatro pessoas.

A Flora cresceu rapidamente e atualmente possui mais de 15 funcionários, um estoque de mais de 20 tipos de flores e uma frota de 4 veículos para entrega. A Flora faturou cerca de R$460.000,00 no ano de 2022.
A Flora se diferencia da concorrência por oferecer um serviço personalizado, onde os clientes podem escolher as flores, as cores, o estilo e a mensagem do arranjo. A Flora também oferece uma garantia de satisfação, onde os clientes podem solicitar a troca ou o reembolso do produto caso não fiquem satisfeitos.
A Flora utiliza as redes sociais, o e-mail marketing e o boca a boca para divulgar seus produtos e atrair novos clientes. A Flora também participa de eventos e feiras relacionados ao segmento de flores e decoração.
A Flora tem como principais desafios manter a qualidade e a variedade das flores, lidar com a sazonalidade e a demanda, gerenciar a logística e a entrega, fidelizar os clientes e expandir o mercado.

Após uma análise sobre os próximos passos da empresa, seus proprietários concluiram que devem atuar como atacadistas e precisma desenvolver toda a estrutura para isso.

Desenvovlimento do Banco de Dados:
O Banco de dados foi desenvolvido no Workbench e contou com quatro planilhas. A planilha de cadastro de clientes, fornecedores, produtos e pedidos. Os aquivos em CSV estaram no mesmo repositório do Github.

Proposta:
Foi solicitado o desenvolvimento de um sistema que utilize uma IA gerativa que crie mensagens personalizadas através do banco de dados da Flora. As mensagens devem estimular clientes a comprar flores para revender e também oferecer dicas de marketing.
"""

import pandas as pd

clientes = pd.read_csv("/content/drive/MyDrive/Estudos_Dados_flora/flora_clientes.csv")
clientes.head()

print(clientes.dtypes)

fornecedores = pd.read_csv("/content/drive/MyDrive/Estudos_Dados_flora/flora_fornecedores.csv")
fornecedores.head()

pedido = pd.read_csv("/content/drive/MyDrive/Estudos_Dados_flora/flora_pedidos - cadastro_cliente_estudo - pedido-3.csv")
pedido.head()

produtos = pd.read_csv("/content/drive/MyDrive/Estudos_Dados_flora/flora_produtos.csv")
produtos.head()

id_clientes = clientes['id_cliente'].tolist()
print(id_clientes)

nome_cliente = clientes['nome_cliente'].tolist()
print(nome_cliente)

!pip install openai

import os
import openai

# Load your API key from an environment variable or secret management service
openai.api_key = os.getenv("ssk-Vzl76VfzKnWPm0L24qjxT3BlbkFJNkkNGrUkvChFYF39h8By")

#chat_completion = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Hello world"}])

openai_api_key = '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'

import openai

openai.api_key = openai_api_key

def generate_ai_news(nome_cliente):
  completion = openai.ChatCompletion.create(
    model="gpt-4",
    messages=[
      {
          "role": "system",
          "content": "Você é uma floricultura e gostaria de ampliar seus clientes que fazem revenda."
      },
      {
          "role": "user",
          "content": f"Crie uma mensagem para {nome_cliente} baseada no nome dos clientes do banco de dados estimulando-os a comprar online e oferecendo dicas de marketing. (máximo de 200 caracteres)"
      }
    ]
  )
  return completion.choices[0].message.content.strip('\"')

for user in nome_cliente:
    if user:  # verifica se o usuário é válido (não vazio, por exemplo)
        news = generate_ai_news(user)
        print(news)
    else:
        print("Usuário inválido encontrado, interrompendo a geração de notícias.")
        break  # interrompe o loop